version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: Passw0rd
    volumes:
      - local_pgdata_fastapi:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mydatabase -U myuser"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a.khabirov@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Passw0rd
    volumes:
      - pgadmin_data_fastapi:/var/lib/pgadmin
    networks:
      - network

volumes:
  local_pgdata_fastapi:
  pgadmin_data_fastapi:

networks:
  network: